CREATE DATABASE grocery_store;
USE grocery_store;

-- 1. Supplier Table
CREATE TABLE IF NOT EXISTS supplier (
    sup_id TINYINT PRIMARY KEY,
    sup_name VARCHAR(255),
    address TEXT
);


-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    cat_id TINYINT PRIMARY KEY,
    cat_name VARCHAR(255)
);

-- 3. Employees Table
CREATE TABLE IF NOT EXISTS employees (
    emp_id TINYINT PRIMARY KEY,
    emp_name VARCHAR(255),
    hire_date VARCHAR(255)
);

-- 4. Customers Table
CREATE TABLE IF NOT EXISTS customers (
    cust_id SMALLINT PRIMARY KEY,
    cust_name VARCHAR(255),
    address TEXT
);

-- 5. Products Table
CREATE TABLE IF NOT EXISTS products (
    prod_id TINYINT PRIMARY KEY,
    prod_name VARCHAR(255),
    sup_id TINYINT,
    cat_id TINYINT,
    price DECIMAL(10,2),
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 6. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    ord_id SMALLINT PRIMARY KEY,
    cust_id SMALLINT,
    emp_id TINYINT,
    order_date VARCHAR(255),
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- 7. Order_Details Table
CREATE TABLE IF NOT EXISTS order_details (
    ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY,
    ord_id SMALLINT,
    prod_id TINYINT,
    quantity TINYINT,
    each_price DECIMAL(10,2),
    total_price DECIMAL(10,2),
    FOREIGN KEY (ord_id) REFERENCES orders(ord_id)
        ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (prod_id) REFERENCES products(prod_id)
        ON UPDATE CASCADE ON DELETE CASCADE
);


-- Analysis Questions

-- 1️. Customer Insights
-- Gain an understanding of customer engagement and purchasing behavior.
-- How many unique customers have placed orders?
SELECT COUNT(DISTINCT cust_id) AS Unique_customers FROM orders;

-- Which customers have placed the highest number of orders?
SELECT c.cust_id, c.cust_name,
COUNT(o.ord_id) AS total_orders
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
GROUP BY cust_id, c.cust_name
HAVING COUNT(o.ord_id) = (SELECT MAX(order_count)
FROM(SELECT COUNT(ord_id) AS
order_count FROM orders
GROUP BY cust_id) t);


-- What is the total and average purchase value per customer?
SELECT
    c.cust_id,
    c.cust_name,
    ROUND(SUM(od.quantity * od.each_price), 2) AS total_purchase_value,
    ROUND(AVG(order_total), 2) AS avg_purchase_value
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
JOIN (
    SELECT
        ord_id,
        SUM(quantity * each_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) ot ON o.ord_id = ot.ord_id
GROUP BY c.cust_id, c.cust_name
ORDER BY total_purchase_value DESC;


-- Who are the top 5 customers by total purchase amount?
SELECT c.cust_name, SUM(od.total_price) AS total_purchase
FROM customers c
JOIN orders o ON c.cust_id = o.cust_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY c.cust_name
ORDER BY total_purchase DESC
LIMIT 5;


-- 2. Product Performance
-- Evaluate how well products are performing in terms of sales and revenue.
-- How many products exist in each category?
SELECT cat.cat_name, COUNT(p.prod_id) AS product_count
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;


-- What is the average price of products by category?
SELECT cat.cat_name, AVG(p.price) AS avg_price
FROM categories cat
JOIN products p ON cat.cat_id = p.cat_id
GROUP BY cat.cat_name;


-- Which products have the highest total sales volume (by quantity)?
SELECT p.prod_name,
       SUM(od.quantity) AS total_quantity
FROM products p
JOIN order_details od
     ON p.prod_id = od.prod_id
GROUP BY p.prod_name
HAVING SUM(od.quantity) = (
    SELECT MAX(total_qty)
    FROM (
        SELECT SUM(quantity) AS total_qty
        FROM order_details
        GROUP BY prod_id) t );


-- What is the total revenue generated by each product?
SELECT p.prod_name, SUM(od.total_price) AS total_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name
ORDER BY total_revenue DESC;


-- How do product sales vary by category and supplier?
SELECT
    c.cat_name as category,
    s.sup_name as supplier,
    SUM(od.quantity) AS total_quantity_sold,
    ROUND(SUM(od.quantity * od.each_price), 2) AS total_revenue
FROM order_details od
JOIN products p ON od.prod_id = p.prod_id
JOIN categories c ON p.cat_id = c.cat_id
JOIN supplier s ON p.sup_id = s.sup_id
GROUP BY c.cat_name, s.sup_name
ORDER BY total_revenue DESC;


-- 3. Sales and Order Trends
-- Analyze business performance through orders and revenue over time.
-- How many orders have been placed in total?
SELECT COUNT(*) AS total_orders
FROM orders;


-- What is the average value per order?
SELECT
    ROUND(AVG(order_total), 2) AS avg_order_value
FROM (
    SELECT
        ord_id,
        SUM(quantity * each_price) AS order_total
    FROM order_details
    GROUP BY ord_id
) t;


-- On which dates were the most orders placed?
SELECT order_date,
COUNT(ord_id) AS total_orders
FROM orders
GROUP BY order_date
ORDER BY total_orders DESC LIMIT 1;


-- What are the monthly trends in order volume and revenue?
-- review
SELECT DATE_FORMAT(o.order_date, '%Y-%m') AS month,
       COUNT(DISTINCT o.ord_id) AS total_orders,
       SUM(od.total_price) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY DATE_FORMAT(o.order_date, '%Y-%m')
ORDER BY month;


-- How do order patterns vary across weekdays and weekends?

ALTER TABLE orders
ADD order_date_dt DATE;
UPDATE orders
SET order_date_dt = STR_TO_DATE(order_date, '%m/%d/%Y');

ALTER TABLE orders
DROP column order_date;

DELETE order_date_ from orders;

select * from orders; 

SET SQL_SAFE_UPDATES = 0;


SELECT * FROM ORDERS;
SELECT
    CASE
        WHEN DAYOFWEEK(o.order_date_dt) IN (1, 7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    ROUND(SUM(od.quantity * od.each_price), 2) AS total_revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_type;

select * from order_details;

-- 4️. Supplier Contribution
-- Identify the most active and profitable suppliers.
-- How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers
FROM supplier;


-- Which supplier provides the most products?
SELECT s.sup_name, COUNT(p.prod_id) AS product_count
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_name
ORDER BY product_count DESC
Limit 1;


-- What is the average price of products from each supplier?
SELECT
    s.sup_name,
    ROUND(AVG(p.price), 2) AS avg_product_price
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
GROUP BY s.sup_id, s.sup_name
ORDER BY avg_product_price DESC;


-- Which suppliers contribute the most to total product sales (by revenue)?
SELECT
    s.sup_name,
    ROUND(SUM(od.quantity * od.each_price), 2) AS total_revenue
FROM supplier s
JOIN products p ON s.sup_id = p.sup_id
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY s.sup_id, s.sup_name
ORDER BY total_revenue DESC
limit 1;

-- 5️. Employee Performance
-- Assess how employees are handling and influencing sales.
-- How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS active_employees
FROM orders;


-- Which employees have handled the most orders?
SELECT e.emp_name, COUNT(o.ord_id) AS total_orders
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
GROUP BY e.emp_name
ORDER BY total_orders DESC
limit 1;


-- What is the total sales value processed by each employee?
SELECT e.emp_name, SUM(od.total_price) AS total_sales
FROM employees e
JOIN orders o ON e.emp_id = o.emp_id
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY e.emp_name;


-- What is the average order value handled per employee?
SELECT e.emp_name,
AVG(order_total) AS avg_order_value
FROM (
    SELECT o.emp_id, o.ord_id, SUM(od.total_price) AS order_total
    FROM orders o
    JOIN order_details od ON o.ord_id = od.ord_id
    GROUP BY o.emp_id, o.ord_id
) t
JOIN employees e ON t.emp_id = e.emp_id
GROUP BY e.emp_name;

-- 6️. Order Details Deep Dive
-- Explore item-level sales patterns and pricing behavior.
-- What is the relationship between quantity ordered and total price?
SELECT quantity, total_price
FROM order_details;


-- What is the average quantity ordered per product?
SELECT p.prod_name, AVG(od.quantity) AS avg_quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_name;


-- How does the unit price vary across products and orders?
SELECT
    p.prod_name as products,
    MIN(od.each_price) AS min_unit_price,
    MAX(od.each_price) AS max_unit_price,
    ROUND(AVG(od.each_price), 2) AS avg_unit_price
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.prod_id, p.prod_name
ORDER BY avg_unit_price DESC;

